FROM apache/airflow:2.7.1

# airflow 사용자에 docker 그룹만 추가
USER root
RUN apt-get update && apt-get install -y docker.io \
    && groupadd - g 999 docker || true \
    && usermod -aG docker airflow
USER airflow